name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: 0 0 * * *}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: [master, main]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

# Options
          user: Thomo1318
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Australia/Sydney
#Plugin_sponserships
          plugin_sponsorships: yes
          plugin_sponsorships_sections: amount, sponsorships
          plugin_sponsorships_size: 24
